# Linear Regression 1D: Prediction

## Table and Contents

1. Prediction
2. Calss Linear
3. Build Custom Modules

In [2]:
import torch
torch.__version__

'1.0.0'

## 1. Presiction

Let's us create the following expression:

b = -1, w = 2

y^ = -1 + 2x

In [4]:
# Define w = 2 and b = -1 for y = wx + b
w = torch.tensor(2.0, requires_grad = True)
b = torch.tensor(-1.0, requires_grad = True)

def forward(x):
    yhat = w * x + b
    return yhat

In [5]:
# Predict y = 2x -1 at x = 1
x = torch.tensor([[1.0]])
yhat = forward(x)
print("The Prediction: ", yhat)

The Prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


In [6]:
# Make the Prediction y = 2x -1 at x = [1, 2]
x = torch.tensor([[1.0],[2.0]])
yhat = forward(x)
print("The Prediction: ", yhat)

The Prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)



## 2. Class Linear

The linear class can be used to make a prediction. We can also use the linear class to build more complex models. Let's import the module:

In [8]:
# Import class Linear
from torch.nn import Linear

In [9]:
# Set random sedd
torch.manual_seed(1)

Let's create the linear object by using the constructor. The parameters are randomly created.

In [10]:
# Create Linear Regression Model, and print out the parameter
lr = Linear(in_features=1, out_features=1, bias=True)
print("The parameter w and b: ", list(lr.parameters()))

The parameter w and b:  [Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [11]:
# A method state_dict() return a Python dictionary object : the layers of each parameters
print("Python dictionary: ",lr.state_dict())
print("keys: ",lr.state_dict().keys())
print("values: ",lr.state_dict().values())

Python dictionary:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
keys:  odict_keys(['weight', 'bias'])
values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [12]:
print("weight:",lr.weight)
print("bias:",lr.bias)

weight: Parameter containing:
tensor([[0.5153]], requires_grad=True)
bias: Parameter containing:
tensor([-0.4414], requires_grad=True)


In [13]:
# Make the Prediction at x = [[1.0]]
x = torch.tensor([[1.0]])
yhat = lr(x)
print("The Prediction: ", yhat)

The Prediction:  tensor([[0.0739]], grad_fn=<AddmmBackward>)


In [14]:
# Make the Prediction at x = [[1.0], [2.0]]
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The Prediction: ", yhat)

The Prediction:  tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)



## 3. Build Costom Modules

Now, let's build a custom module. We can make more complex models by using this method later on. 

In [15]:
from torch import nn

Now, let's define the class:

In [16]:
# Customize Linear Regression Class
class LR(nn.Module):
    # Constructor
    def __init__(self, input_size, output_size):
        # Inheirt from parent
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    # Prediction function
    def forward(self, x):
        out = self.linear(x)
        return out

In [17]:
# Create the Linear Regression model. Print out the pareameters
lr = LR(1, 1)
print("The parameters: ", list(lr.parameters()))
print("Linear Model: ", lr.linear)

The parameters:  [Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
Linear Model:  Linear(in_features=1, out_features=1, bias=True)


In [18]:
# Make the Prediction at x = [[1.0], [2.0]]
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print("The Prediction: ", yhat)

The Prediction:  tensor([[0.2755],
        [0.0816]], grad_fn=<AddmmBackward>)


In [21]:
# Parameters are also stored in an ordered dictionary
print("Python dictionary: ", lr.state_dict())
print("keys: ", lr.state_dict().keys())
print("values: ", lr.state_dict().values())

Python dictionary:  OrderedDict([('linear.weight', tensor([[-0.1939]])), ('linear.bias', tensor([0.4694]))])
keys:  odict_keys(['linear.weight', 'linear.bias'])
values:  odict_values([tensor([[-0.1939]]), tensor([0.4694])])
